# version: 2.1
# orbs:
#   node: circleci/node@1.1.6
# jobs:
#   build-and-test:
#     executor:
#       name: node/default
#     steps:
#       - checkout
#       - node/with-cache:
#           steps:
#             - run: npm install
version: 2
jobs:
  test:
    docker:
      - image: "circleci/node:9.11.2"
    steps:
      - checkout
      - run:
          name: Download depencies
          command: npm install
      - run:
          name: Test
          command: yarn test
